name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: shutdown msql
        run: sudo service mysql stop
      - name: setup maria
        uses: getong/mariadb-action@v1.1
        with:
          host port: 3308
          container port: 3308
          character set server: "utf8"
          msql database: "tester"
          mysql root password: "123456"
      - name: add database
        run: mysql -u root -p tester < tester.sql
        working-directory: ./app
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: ./app
      - run: npm run build --if-present
        working-directory: ./app
      - run: npm test
        working-directory: ./app
        env:
          CI: true
