on: push
name: npm build, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - name: setup mariadb
        uses: getong/mariadb-action@v1.1
        with:
          host port: 3308
          container port: 3308
          character set server: 'utf8'
          msql database: 'tester'
          mysql root password: '123456'
      - name: add database
        run: mysql -u root -p tester < tester.sql
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@master
        with:
          args: install
      - name: npm test
        uses: actions/npm@master
        with:
          args: run test
      - name: docker build
        uses: actions/docker/cli@master
        with:
          args: build -t rainerbonilla/typeAPInode .
      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        uses: actions/docker/cli@master
        with:
          args: push rainerbonilla/typeAPInode
